[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.9

[font.normal]
family = "JetBrainsMono NF"
# family = "Maple Mono NF"
# family = "CaskaydiaCove NF"
style = "SemiBold"

[general]
import = ["/home/denzel/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.65
blur = true
decorations = "None"
dynamic_padding = true

[window.dimensions]
columns = 106
lines = 31

[window.padding]
# x = 3
# y = 3
